### ISSUE TITLE
gpsup logo

### ISSUE THREAD

**Issue by ivannewgate89** [2ruslan/GpsUp#3]
hi, i want to participate in gpsup logo project, thanks

**Comment by 2ruslan** [comment]
hello! what are your ideas? )

**Comment by ivannewgate89** [comment]
Hi well, I thought I would make a logo with a more simple look and looks
more fresh, and I will soon be completed, thank you

Pada tanggal 22 Mar 2018 6.33 PM, "ruslan kupchinskii" <
notifications@github.com> menulis:

**Comment by ivannewgate89** [comment]
![dfasdfadfafa](https://user-images.githubusercontent.com/37645987/37810417-942794ca-2e86-11e8-94f8-7a6d742b41b1.png)
hello ruslan, this is my idea for concept logo GPS UP

**Comment by jol09** [comment]
let me give you advice about your latest logo.
and if you let me make the latest logo and I take the symbol of the finger
today. I thought it would look modern and compotible
Pada tanggal 23 Mar 2018 10:42, "ivannewgate89" <notifications@github.com>
menulis:

**Comment by ivannewgate89** [comment]
sorry before, I do not understand the meaning of the finger symbol, does not reduce the value of the GPS icon if replaced with a finger symbol? maybe i have try to make your idea, thanks

**Comment by ivannewgate89** [comment]
![gps up 2](https://user-images.githubusercontent.com/37645987/37815830-2351cf64-2ea3-11e8-9826-116031fe6b72.png)
how about this, are you like?

**Comment by 2ruslan** [comment]
Hello! thanks, but now the logo looks good)

**Comment by ivannewgate89** [comment]
Fiverr
    
    
            
      {
          "@context": "http://schema.org",
          "@type": "EmailMessage",
          "action": {
            "@type": "ViewAction",
            "url": "https://www.fiverr.com/s2/c9383ce5ff",
            "name": "Browse Services on Fiverr"
          },
          "description": "Browse Services on Fiverr"
      }
    

        
            
                
                    
                        
                            
                                
                                    
                                        
                                    
                                
                                
                                    
                                    
                                
                                
                                    

                                        
    

    
        Irvan is tired of keeping Fiverr a secret.
    

    
        Fiverr is the world’s largest marketplace for services,where you can get everything you need at an unbeatable value.
    

    
        Sounds too good to be true? See for yourself!
    



                                        
                                            
                                                
                                                    
                                                        
                                                            Browse Services On Fiverr
                                                        
                                                    
                                                
                                                
                                                    
                                                        

		
			
			
			The Fiverr Team
		
                                                    
                                                
                                            
                                        
                                    
                                
                            
                        
                    
                
                
                    
                        
                            
                                

                                    © Fiverr International Limited 2010-2016, Fiverr Inc. | 401 Broadway, Suite 1600 New York NY, 10013 USA.
                                    Your personal information will not be stored or used for any marketing purposes.
                                
                            
                         
                    
                
            
        
            

    

If you would like to unsubscribe and stop receiving these emails click here.
